spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5433/userdb
    username: leduyhai
    password: 272004
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8082

