spring:
  datasource:
    url: jdbc:postgresql://${NEON_PRODUCT_URL}
    username:  ${NEON_USERNAME}
    password: ${NEON_PASSWORD}

  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
