spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_PRODUCT_NAME:productdb}
    username:  ${DB_USERNAME:leduyhai}
    password: ${DB_PASSWORD:272004}

  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
